blank_issues_enabled: false
contact_links:
  - name: Bugs in Add-on code ğŸ
    url: https://github.com/FiltersHeroes/PolishCookieConsent/issues/new?template=bug.yml
    about: Please submit bugs in Add-on code via the Polish Cookie Consent repository. ğŸ™‚
